language: go
go: 1.3

services:
  - mongodb

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/lealife/test
  - ls
  - ls -A
  - ls /
  - pwd

script:
  - mongo --version
  - ls -A
  - go run a.go