language: go
go: 1.3

services:
  - mongodb # 2.4.12

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/lealife/test
  - ls
  - ls -A
  - ls /
  - pwd

script:
  - mongo --version
  - mongorestore -h localhost -d leanote --directoryperdb ./mongodb_backup/leanote_install_data/
  - ls -A
  - go run a.go